version: "3.8"
services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: quotes_dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d quotes_dev"]
      interval: 2s
      timeout: 2s
      retries: 15
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  api:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      ConnectionStrings__Default: "Host=db;Port=5432;Database=quotes_dev;Username=postgres;Password=postgres"
      ASPNETCORE_ENVIRONMENT: "Development"
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/ready"]
      interval: 5s
      timeout: 2s
      retries: 15

volumes:
  pgdata:
